version: '3.8'   # docker-compose 버전
services:        # 실행할 컨테이너들을 정의
  mysql:         # MySQL 서비스 정의
    image: mysql:8.0                # 사용할 MySQL 이미지
    container_name: mysql_local     # 컨테이너 이름
    ports:
      - "3307:3306"                # 호스트:컨테이너 포트 매핑
    environment:                    # 환경변수 설정
      MYSQL_ROOT_PASSWORD: rootpassword     # root 계정 비밀번호
      MYSQL_DATABASE: myapp                 # 생성할 데이터베이스 이름
      MYSQL_USER: user                      # 생성할 사용자 이름
      MYSQL_PASSWORD: userpassword          # 사용자 비밀번호
    volumes:                        # 데이터 영구 저장을 위한 볼륨 설정
      - mysql_data:/var/lib/mysql
  
  redis:         # Redis 서비스 정의
    image: redis:latest
    container_name: redis_local
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:         # 도커 볼륨 정의
  mysql_data:    # MySQL 데이터 저장용 볼륨
  redis_data:    # Redis 데이터 저장용 볼륨